name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: 
        echo ${{ secrets.A_SECRET }}
        echo ${{ secrets.A_SECRET }} | base64
   
